### ISSUE TITLE
会有挺多目标不会进行跟踪

### ISSUE THREAD

**Issue by Rainweic** [weixu000/libtorch-yolov3-deepsort#23]
您好 我使用yolov5作为检测器 但是发现检测到的目标特别多的时候 有挺大部分的bbox并不会进行追踪 请问这个要怎么调整呢 能否留个联系方式 我把源码发给你瞅瞅

**Comment by yasenh** [comment]
Hi @Rainweic, based on the deepsort paper "These new tracks are classified as tentative during their first 3 frames". So I guess maybe some of your bbox does not have stable detections during 3 consecutive frames, that's why they are not tracked.   
E.g. you can find similar parameter from [This deepsort pytorch version](https://github.com/ZQPei/deep_sort_pytorch/blob/master/configs/deep_sort.yaml#L8). 

BTW: I am also exploring integrate yolov5 and deepsort in C++, maybe I can share additional experience with you later on
